language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

before_script:
  - composer self-update
  - composer install
  - composer global require satooshi/php-coveralls codeclimate/php-test-reporter
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_script:
  - travis_retry coveralls -v

after_success:
  - travis_retry test-reporter

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

addons:
  code_climate:
    repo_token: abcf655c83810e4db2924f6f3be83db60306352fee60a05bd158fa2905403080