---
version: '3.0'

services:
  composer:
    image: herloct/composer:1.3.2-php7.1
    volumes:
      - .:/project

  phpunit:
    image: php:7.1.2-alpine
    entrypoint: phpdbg -qrr vendor/bin/phpunit
    working_dir: /project
    volumes:
      - .:/project

  phpstan:
    image: phpstan/phpstan
    working_dir: /project
    volumes:
      - .:/project

  phpcs:
    image: herloct/phpcs:2.8.0
    volumes:
      - .:/project

  phpcbf:
    image: herloct/phpcbf:2.8.0
    volumes:
      - .:/project